### ISSUE TITLE
[Anon] Battlegroup: Legio Audax is not available to be chosen

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/at-2018#28] opened 2024-09-26 20:33 UTC
**Problem:**
Legio Audax is not available to be chosen

**Expected:**
Legio Audax can be chosen and the reaver can be replaced by a direwolf

 **Additional Info:**
the heavy scout titan rule.

**List:** https://www.newrecruit.eu/app/list/VlSTm
**Unit:** Venator Light Maniple, id: 5192-e107-566f-52c7

**Comment by jorisvangestel** [comment] 2024-11-29 20:03
This is a duplicate of #23

**Closed by jorisvangestel** 2024-11-29 20:03 UTC
Labels: duplicate
